import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
<<<<<<< HEAD
import { ContextGlobalProvider } from '@/context/Context';
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from 'react-toastify';
=======
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import StoreProvider from '@/components/StoreProvider';
>>>>>>> main

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <ContextGlobalProvider>
          <Header />
          {children}
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            closeOnClick
            draggable
          />
          <Footer />
        </ContextGlobalProvider>
=======
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>

        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          closeOnClick
          draggable
        />
>>>>>>> main
      </body>
    </html>
  );
}
